#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=99

 
start() {        
        echo start
        # commands to launch application
	python /root/checkBridge.py &
	
}                 
 
stop() {          
        echo stop
        # commands to kill application 
}
